// AUTO-GENERATED by scripts/generate-narration.mjs — do not edit.
/* eslint-disable */
export const NARRATION_AUDIO = {
  "hero": require("../../../assets/narration/hero.mp3"),
  "marquee": require("../../../assets/narration/marquee.mp3"),
  "ch-calls": require("../../../assets/narration/ch-calls.mp3"),
  "ch-meetings": require("../../../assets/narration/ch-meetings.mp3"),
  "ch-search": require("../../../assets/narration/ch-search.mp3"),
  "ch-voice": require("../../../assets/narration/ch-voice.mp3"),
  "ch-alarms": require("../../../assets/narration/ch-alarms.mp3"),
  "how": require("../../../assets/narration/how.mp3"),
  "callees": require("../../../assets/narration/callees.mp3"),
  "stats": require("../../../assets/narration/stats.mp3"),
  "faq": require("../../../assets/narration/faq.mp3"),
  "final": require("../../../assets/narration/final.mp3"),
} as const;
