import { z } from "zod";
declare const EnvSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "production"]>>;
    API_PORT: z.ZodDefault<z.ZodNumber>;
    API_HOST: z.ZodDefault<z.ZodString>;
    DATABASE_URL: z.ZodString;
    REDIS_URL: z.ZodString;
    ANTHROPIC_API_KEY: z.ZodString;
    ANTHROPIC_MODEL: z.ZodDefault<z.ZodString>;
    ELEVENLABS_API_KEY: z.ZodString;
    ELEVENLABS_VOICE_ID: z.ZodString;
    ELEVENLABS_MODEL_ID: z.ZodDefault<z.ZodString>;
    TWILIO_ACCOUNT_SID: z.ZodString;
    TWILIO_AUTH_TOKEN: z.ZodString;
    TWILIO_PHONE_NUMBER: z.ZodString;
    DEEPGRAM_API_KEY: z.ZodString;
    JWT_SECRET: z.ZodString;
    JWT_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    WORKER_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    RATE_LIMIT_CALLS_PER_HOUR: z.ZodDefault<z.ZodNumber>;
    RATE_LIMIT_AI_RPM: z.ZodDefault<z.ZodNumber>;
    VOICE_SESSION_MAX_DURATION_S: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "test" | "production";
    API_PORT: number;
    API_HOST: string;
    DATABASE_URL: string;
    REDIS_URL: string;
    ANTHROPIC_API_KEY: string;
    ANTHROPIC_MODEL: string;
    ELEVENLABS_API_KEY: string;
    ELEVENLABS_VOICE_ID: string;
    ELEVENLABS_MODEL_ID: string;
    TWILIO_ACCOUNT_SID: string;
    TWILIO_AUTH_TOKEN: string;
    TWILIO_PHONE_NUMBER: string;
    DEEPGRAM_API_KEY: string;
    JWT_SECRET: string;
    JWT_EXPIRES_IN: string;
    WORKER_CONCURRENCY: number;
    RATE_LIMIT_CALLS_PER_HOUR: number;
    RATE_LIMIT_AI_RPM: number;
    VOICE_SESSION_MAX_DURATION_S: number;
}, {
    DATABASE_URL: string;
    REDIS_URL: string;
    ANTHROPIC_API_KEY: string;
    ELEVENLABS_API_KEY: string;
    ELEVENLABS_VOICE_ID: string;
    TWILIO_ACCOUNT_SID: string;
    TWILIO_AUTH_TOKEN: string;
    TWILIO_PHONE_NUMBER: string;
    DEEPGRAM_API_KEY: string;
    JWT_SECRET: string;
    NODE_ENV?: "development" | "test" | "production" | undefined;
    API_PORT?: number | undefined;
    API_HOST?: string | undefined;
    ANTHROPIC_MODEL?: string | undefined;
    ELEVENLABS_MODEL_ID?: string | undefined;
    JWT_EXPIRES_IN?: string | undefined;
    WORKER_CONCURRENCY?: number | undefined;
    RATE_LIMIT_CALLS_PER_HOUR?: number | undefined;
    RATE_LIMIT_AI_RPM?: number | undefined;
    VOICE_SESSION_MAX_DURATION_S?: number | undefined;
}>;
export type Env = z.infer<typeof EnvSchema>;
export declare const config: Env;
export {};
//# sourceMappingURL=index.d.ts.map